### ISSUE TITLE
clang-tidy is not found when installed in a custom path

### ISSUE THREAD

**Issue by aminya** [erenon/bazel_clang_tidy#19]
clang-tidy is not found in run_clang_tidy.sh although it is on the PATH. It seems that the spawn doesn't pass the env variables.
https://github.com/erenon/bazel_clang_tidy/blob/783aa523aafb4a6798a538c61e700b6ed27975a7/clang_tidy/run_clang_tidy.sh#L14

**Comment by erenon** [comment]
Do you have --action_env specified?

**Comment by aminya** [comment]
No, as far as I have set. Maybe my dependencies set that. I can check and get back to you

**Comment by aminya** [comment]
I checked. I didn't specify that. I hope it can be fixed.

I have found a hacky workaround to hot patch the clang_tidy path using [go-task](https://taskfile.dev/#/)
```yaml
  clang_tidy_path:
    cmds:
      - sed -i '/^clang-tidy "\$@"$/s|clang-tidy|{{.HOME}}/llvm/bin/clang-tidy/|' {{.run_clang_tidy}}
    preconditions:
      - test -f {{.run_clang_tidy}}
    vars:
      run_clang_tidy: ./bazel-myproj/external/bazel_clang_tidy/clang_tidy/run_clang_tidy.sh

  tidy:
    cmds:
      - task: clang_tidy_path
      - bazel build --config=tidy myproj
```
